version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017" # Maps MongoDB port to the host
    volumes:
      - mongodb_data:/data/db # Persists data
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin # Set admin username
      MONGO_INITDB_ROOT_PASSWORD: password # Set admin password

volumes:
  mongodb_data:
